import { Carousel } from "@/components/Carousel";
import { PROJECT_IDS } from "@/data/projects";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>GSAP Page Transitions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Carousel items={PROJECT_IDS} />
      </main>
    </>
  );
}
